/* ============================================================
   build.js — generates the hosted bundle from the source HTML.

   The single-file `sq-rugby-registration-form.html` stays the
   editable SOURCE (and a standalone local preview). This script
   extracts its <style> + form-logic <script> and writes a
   self-contained `sq-rugby-registration-form.js` that:
     • carries all built-in defaults (everything except the
       per-page targetSectionId),
     • injects its own CSS at runtime,
     • runs the same form logic.

   Usage:  node build.js
   ============================================================ */

const fs = require('fs');
const path = require('path');

const dir = __dirname;
const SRC = path.join(dir, 'sq-rugby-registration-form.html');
const OUT = path.join(dir, 'sq-rugby-registration-form.js');

const html = fs.readFileSync(SRC, 'utf8');

/* 1) Styles — the single <style> block. */
const cssMatch = html.match(/<style>([\s\S]*?)<\/style>/);
if (!cssMatch) throw new Error('Could not find the <style> block.');
const css = cssMatch[1].trim();

/* 2) Built-in defaults — the config object literal, minus targetSectionId
      (that one is set per-page, in the page header injection). */
const cfgMatch = html.match(/window\.SQ_RUGBY_FORM_CONFIG\s*=\s*(\{[\s\S]*?\});/);
if (!cfgMatch) throw new Error('Could not find the SQ_RUGBY_FORM_CONFIG object.');
let defaults = cfgMatch[1]
  // drop the per-page targetSectionId line
  .replace(/^[^\n]*targetSectionId[^\n]*\n/m, '')
  // drop the now-orphaned "CHANGE THIS PER PAGE" banner comment lines
  .replace(/^[ \t]*\/\/[^\n]*(?:CHANGE THIS PER PAGE|data-section-id|═)[^\n]*\n/gm, '');

/* 3) Form logic — the <script> that follows the "Form Injection + Logic" note. */
const logicMatch = html.match(/Form Injection \+ Logic[\s\S]*?-->\s*<script>([\s\S]*?)<\/script>/);
if (!logicMatch) throw new Error('Could not find the form-logic <script> block.');
const logic = logicMatch[1].trim();

const out =
`/* ============================================================
   Junior Community Rugby Festivals — Registration Form
   HOSTED BUNDLE  (styles + logic + built-in defaults)

   ⚠ AUTO-GENERATED from sq-rugby-registration-form.html by build.js
   Do NOT edit this file by hand. Edit the .html, then run:  node build.js

   On each Squarespace page, the header injection only needs:
     <script>window.SQ_RUGBY_FORM_CONFIG = { targetSectionId: "THIS_PAGE_SECTION_ID" };</script>
     <script src="https://cdn.jsdelivr.net/gh/USER/REPO@main/sq-rugby-registration-form.js"></script>
   ============================================================ */
(function () {
  'use strict';
  if (window.__SQRF_LOADED__) return;        // guard against double-load
  window.__SQRF_LOADED__ = true;

  /* Built-in defaults — every page shares these; only targetSectionId differs. */
  var DEFAULTS = ${defaults};

  /* Merge: page-provided config (targetSectionId, or any override) wins. */
  window.SQ_RUGBY_FORM_CONFIG = Object.assign({}, DEFAULTS, window.SQ_RUGBY_FORM_CONFIG || {});

  /* Inject the form's styles once. */
  if (!document.getElementById('sqrf-styles')) {
    var styleEl = document.createElement('style');
    styleEl.id = 'sqrf-styles';
    styleEl.textContent = ${JSON.stringify(css)};
    (document.head || document.documentElement).appendChild(styleEl);
  }

  /* ---- Form logic (verbatim from sq-rugby-registration-form.html) ---- */
  ${logic}
})();
`;

fs.writeFileSync(OUT, out, 'utf8');
console.log('Wrote ' + path.basename(OUT) + ' (' + out.length + ' bytes)');
